package com.dbmi.demos.quiz;

/**
 * TODO Autogenerated javadoc comment.
 */
public class QuizException extends Exception {
   public QuizException(String theMessage) {
      super(theMessage);
   }
}
